
const mealPlans = {
  Underweight: {
    title: "Underweight Meal Plan",
    days: [
      {
        day: "Monday",
        breakfast: "3 boiled eggs + 1 glass of milk + 4 almonds",
        lunch: "Rice + dal + chicken curry + curd",
        evening: "Banana shake + nuts",
        dinner: "2 chapatis + paneer curry + salad",
        calories: 3000,
        energy: 12552,
        proteins: 120,
      },
      {
        day: "Tuesday",
        breakfast: "Paratha + curd + banana",
        lunch: "Rice + rajma + sabji + salad",
        evening: "Milkshake + groundnuts",
        dinner: "Chapati + chicken/fish + dal",
        calories: 2950,
        energy: 12358,
        proteins: 115,
      },
      {
        day: "Wednesday",
        breakfast: "Oats + milk + apple",
        lunch: "Rice + dal fry + egg curry",
        evening: "Fruit juice + nuts",
        dinner: "Chapati + paneer + vegetables",
        calories: 2900,
        energy: 12148,
        proteins: 110,
      },
      {
        day: "Thursday",
        breakfast: "Dosa + chutney + milk",
        lunch: "Rice + sambar + chicken curry",
        evening: "Banana + nuts",
        dinner: "Chapati + dal + sabji",
        calories: 2950,
        energy: 12358,
        proteins: 112,
      },
      {
        day: "Friday",
        breakfast: "Idli + sambar + milk",
        lunch: "Rice + dal + sabji + curd",
        evening: "Fruit smoothie",
        dinner: "Chapati + chicken curry + salad",
        calories: 2920,
        energy: 12226,
        proteins: 113,
      },
      {
        day: "Saturday",
        breakfast: "Bread toast + boiled eggs + milk",
        lunch: "Rice + rajma + sabji",
        evening: "Banana shake + dry fruits",
        dinner: "Chapati + paneer curry + dal",
        calories: 3000,
        energy: 12552,
        proteins: 118,
      },
      {
        day: "Sunday",
        breakfast: "Poori + potato curry + milk",
        lunch: "Rice + dal + fish curry",
        evening: "Milkshake + nuts",
        dinner: "Chapati + egg curry + salad",
        calories: 3050,
        energy: 12768,
        proteins: 120,
      },
    ],
  },

  Normal: {
    title: "Balanced Diet Plan",
    days: [
      {
        day: "Monday",
        breakfast: "Idli + sambar + chutney",
        lunch: "Rice + dal + sabji + salad",
        evening: "Fruits + nuts",
        dinner: "Chapati + dal fry + vegetables",
        calories: 2000,
        energy: 8370,
        proteins: 65,
      },
      {
        day: "Tuesday",
        breakfast: "Poha + tea",
        lunch: "Rice + sambar + curd + sabji",
        evening: "Buttermilk + nuts",
        dinner: "Chapati + sabji + dal",
        calories: 2050,
        energy: 8580,
        proteins: 68,
      },
      {
        day: "Wednesday",
        breakfast: "Dosa + chutney",
        lunch: "Rice + dal fry + sabji + salad",
        evening: "Fruit juice",
        dinner: "Chapati + chicken curry (light)",
        calories: 2100,
        energy: 8790,
        proteins: 72,
      },
      {
        day: "Thursday",
        breakfast: "Oats + milk",
        lunch: "Rice + rasam + vegetables",
        evening: "Fruits",
        dinner: "Chapati + dal fry + sabji",
        calories: 2000,
        energy: 8370,
        proteins: 66,
      },
      {
        day: "Friday",
        breakfast: "Upma + chutney",
        lunch: "Rice + dal + sabji + salad",
        evening: "Buttermilk",
        dinner: "Chapati + fish curry (light)",
        calories: 2050,
        energy: 8580,
        proteins: 70,
      },
      {
        day: "Saturday",
        breakfast: "Bread + milk",
        lunch: "Rice + rajma + sabji",
        evening: "Fruits + nuts",
        dinner: "Chapati + dal + vegetables",
        calories: 2000,
        energy: 8370,
        proteins: 68,
      },
      {
        day: "Sunday",
        breakfast: "Idli + chutney",
        lunch: "Rice + dal fry + curd",
        evening: "Fruit juice",
        dinner: "Chapati + sabji + dal",
        calories: 1980,
        energy: 8290,
        proteins: 66,
      },
    ],
  },

  Overweight: {
    title: "Weight Loss Meal Plan",
    days: [
      {
        day: "Monday",
        breakfast: "Oats + green tea",
        lunch: "Brown rice + dal + sabji",
        evening: "Sprouts + lemon juice",
        dinner: "Chapati + sabji + dal",
        calories: 1600,
        energy: 6700,
        proteins: 55,
      },
      {
        day: "Tuesday",
        breakfast: "Idli (steamed) + sambar",
        lunch: "Quinoa + dal + sabji",
        evening: "Buttermilk",
        dinner: "Vegetable soup + chapati",
        calories: 1550,
        energy: 6487,
        proteins: 50,
      },
      {
        day: "Wednesday",
        breakfast: "Ragi porridge",
        lunch: "Brown rice + dal + vegetables",
        evening: "Fruits",
        dinner: "Chapati + sabji (less oil)",
        calories: 1600,
        energy: 6700,
        proteins: 52,
      },
      {
        day: "Thursday",
        breakfast: "Vegetable sandwich (brown bread)",
        lunch: "Rice + dal + sabji",
        evening: "Green tea + nuts",
        dinner: "Soup + salad",
        calories: 1580,
        energy: 6610,
        proteins: 50,
      },
      {
        day: "Friday",
        breakfast: "Upma + chutney",
        lunch: "Millet khichdi + sabji",
        evening: "Fruits + sprouts",
        dinner: "Chapati + dal fry",
        calories: 1600,
        energy: 6700,
        proteins: 52,
      },
      {
        day: "Saturday",
        breakfast: "Idli + chutney",
        lunch: "Rice + dal + sabji",
        evening: "Buttermilk",
        dinner: "Soup + chapati",
        calories: 1550,
        energy: 6487,
        proteins: 50,
      },
      {
        day: "Sunday",
        breakfast: "Oats + fruits",
        lunch: "Quinoa + dal + sabji",
        evening: "Fruits",
        dinner: "Chapati + sabji",
        calories: 1600,
        energy: 6700,
        proteins: 52,
      },
    ],
  },

  Obese: {
    title: "Obesity-Friendly Meal Plan",
    days: [
      {
        day: "Monday",
        breakfast: "Green smoothie (spinach + cucumber)",
        lunch: "Salad + dal",
        evening: "Fruits",
        dinner: "Clear veg soup + chapati",
        calories: 1400,
        energy: 5860,
        proteins: 45,
      },
      {
        day: "Tuesday",
        breakfast: "Oats + skimmed milk",
        lunch: "Millet + dal + sabji",
        evening: "Carrot + cucumber sticks",
        dinner: "Clear soup",
        calories: 1350,
        energy: 5680,
        proteins: 42,
      },
      {
        day: "Wednesday",
        breakfast: "Vegetable juice",
        lunch: "Brown rice + sabji",
        evening: "Fruits",
        dinner: "Chapati + dal soup",
        calories: 1400,
        energy: 5860,
        proteins: 44,
      },
      {
        day: "Thursday",
        breakfast: "Ragi dosa + chutney",
        lunch: "Salad + sprouts",
        evening: "Green tea + fruits",
        dinner: "Soup + chapati",
        calories: 1370,
        energy: 5735,
        proteins: 43,
      },
      {
        day: "Friday",
        breakfast: "Idli (steamed) + chutney",
        lunch: "Quinoa + dal + sabji",
        evening: "Fruits",
        dinner: "Clear veg soup",
        calories: 1380,
        energy: 5780,
        proteins: 43,
      },
      {
        day: "Saturday",
        breakfast: "Upma (less oil)",
        lunch: "Brown rice + sabji",
        evening: "Buttermilk",
        dinner: "Chapati + dal fry",
        calories: 1400,
        energy: 5860,
        proteins: 44,
      },
      {
        day: "Sunday",
        breakfast: "Oats porridge",
        lunch: "Millet khichdi + vegetables",
        evening: "Fruit bowl",
        dinner: "Clear soup + chapati",
        calories: 1360,
        energy: 5690,
        proteins: 42,
      },
    ],
  },
};

export default mealPlans;
